server:
  port: 2221

spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: hello-service
    api-b:
      path: /api-b/**
      service-id: feign-consumer
  # 敏感的请求头信息，zuul在请求路由时会自动过滤掉相关的请求头，防止它们被传递到下游服务器中
  sensitive-headers:
    - Cookie
    - Set-Cookie
    - Authorization
  # Flag to determine whether the proxy forwards the Host header.
  # 使得网关在进行路由转发前为请求设置host头信息，以标识最初的服务端请求地址
  add-host-header: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka